README.md

fix filename

---

harpia/manifest.xml

https://github.com/Halium/projectmanagement/issues/34

Add device harpia (Motorola G4 Play)

---

mako/manifest.xml

Added Google Nexus 4 (mako) as device

Add new device Nexus 4 (mako)

---

manifests/sony_dogo.xml
manifests/sony_odin.xml
manifests/sony_pollux.xml
manifests/sony_pollux_windy.xml

This includes the devices dogo (Sony Xperia ZR), oding (Sony Xperia ZL),
pollux (Sony Xperia Tablet Z), pollux_windy (Sony Xperia Tablet Z WiFi).

Add all sony fusion3 devices

---

setup

This will make the output when doing repo sync much more clean.

Sync in quiet mode

---

manifests/oneplus_cheeseburger.xml

cheeseburger: Add missing Halium/ in repo names

---

manifests/zuk_z2_plus.xml

<?xml version="1.0" encoding="UTF-8"?>
<manifest>
<project path="device/zuk/z2_plus" name="android_device_zuk_z2_plus" remote="my" revision="cm-14.1" />
<project path="device/zuk/msm8996-common" name="android_device_zuk_msm8996-common" remote="my" revision="cm-14.1" />
<project path="device/qcom/sepolicy" name="android_device_qcom_sepolicy" remote="my2" revision="cm-14.1" />
<project path="vendor/zuk" name="proprietary_vendor_zuk" remote="my" revision="cm-14.1" />
<project path="kernel/zuk/z2_plus" name="android_kernel_zuk_msm8996" remote="my" revision="cm-14.1" />	
<project path="vendor/qcom/opensource/cryptfs_hw" name="android_vendor_qcom_opensource_cryptfs_hw" remote="los" revision="cm-14.1"  />
<remote name="my"
fetch="https://github.com/z2-dev"
revision="cm-14.1" />
<remote …

Add zuk (z2_plus)

---

manifests/motorola_titan.xml

Add Motorola device titan (Moto G 2014)

add motorola titan

---

manifests/motorola_shamu.xml

Hopefully this all works right. I haven't touched it in a while.

Add shamu manifest

---

manifests/bq_chaozu.xml
manifests/bq_tenshi.xml
manifests/motorola_harpia.xml
manifests/motorola_lux.xml
manifests/motorola_merlin.xml
manifests/motorola_osprey.xml
manifests/motorola_potter.xml
manifests/motorola_surnia.xml

As per: https://github.com/Halium/android/pull/14#issuecomment-369958256
In order to prevent repo from breaking.

halium-devices: Remove bson since it's now part of default.xml

---

manifests/oneplus_oneplus3.xml

Change-Id: I18cef26ea46c02726205db6d3a72ee4ed7f583d8

Add OnePlus 3 / 3T (oneplus3)

---

manifests/samsung_dream2lte.xml

Can already produce a working build in it's current state

Add Samsung Galaxy S8+ (Exynos) (dream2lte)

---

manifests/xiaomi_santoni.xml

Now points to Nikesh001's repo.
Please, next time request changes before merging the PR.
Thanks!

santoni: Updated manifest

---

manifests/fairphone_FP2.xml
manifests/lge_hammerhead.xml
manifests/motorola_titan.xml

*Add xml encoding tag
*Unify spacing (spaces vs mixture)
*Order project paths alphabetically
Signed-off-by: Herman van Hazendonk github.com@herrie.org

halium-devices: Make files consistent

---

setup

Seems that some vendors stuff bits in their vendor common repo as well.
Let's tackle that one too.

Setup: Add possibility to check the vendor common trees as well.

---

manifests/xiaomi_mido.xml

https://github.com/Halium/projectmanagement/issues/71

Add Xiaomi Redmi Note 4 (mido)

---

manifests/oneplus_oneplus2.xml

Add OnePlus 2 manifest for halium 5.1
halium 7.1 will come soon

Add OnePlus 2 (oneplus2)

---

manifests/oneplus_oneplus2.xml

add oneplus2 manifest for halium-7.1

Add oneplus2 manifest

---

manifests/oneplus_onyx.xml

Add OnePlus X (onyx)

---

manifests/xiaomi_land.xml

Update remote in xiaomi_land.xml

---

setup

This should make the relevant files easier to find from the status messages.

Use full pathes in status messages

---

setup

Herrie prefers it with the brackets, but I think it's easier to read without it... So I'm proposing a simplification, but feel free to either merge or refuse it :-)

Simplify regexps a bit

---

manifests/samsung_klte.xml

with modified kernel (android_kernel_samsung_msm8974)
and modified device tree (android_device_samsung_klte-common)

Klte: modify Samsung Galaxy S5 manifest

---

manifests/sony_suzuran.xml

Based on the sumire setup - just a differen kernel configuration and a new device repository.

Add suzuran: Sony Z5 compact

---

manifests/sony_karin.xml
manifests/sony_karin_windy.xml

Based on the z5 setup. The hardware is very similar only a different touchscreen and larger screen, and probably a different gps.

Add Sony Z4 in LTE and Wifi Only mode to halium

---

manifests/motorola_cedric.xml

I deviated from the instructions/.dependencies file a bit, copying what other Qualcomm devices have used as I ran into some issue.
I don't believe this has caused any problems thus far.

Add Motorola Moto G5 (cedric)

---

manifests/xiaomi_land.xml

repos updated, bcoz it use entirely different sources

Updated repo from maintainer

---

manifests/lge_rs988.xml

manifest created but, further porting needed

Add support for LGE G5 rs988 

---

manifests/samsung_serranodsdd.xml

Change-Id: Ib6c6c12211c9b1a54df245691fc7f1ad9ae7d9b3

Add s4mini manifest (with remote kernel for now, still WIP)

---

manifests/htc_m8qlul.xml

Change-Id: I01d90fcc186d37a45bad5bc3bcde1c2e79dbd986
NOTE: Repo is probably temporary

Add HTC One M8s (m8qlul)

---

manifests/xiaomi_tissot.xml

Use Tofee's repos, forked from a better LineageOS source
Change-Id: I3b2b7ddb00ed3047924d422a03954db12e7fc20e

tissot: update repos

---

manifests/motorola_athene.xml

Moved and started over, to keep clean things.

Update athene GitHub url

---

manifests/xiaomi_markw.xml

Change-Id: I460571d3fe032716598587ec22d4ae7f6e7f48ce

Added manifest for xiaomi_markw

---

manifests/sony_suzu.xml

Relevant change: d5958aa
All other changes are due to the merge from Halium into my repo.

suzu: change fetch remote

---

manifests/zte_axon7.xml

Using my device tree should allow for more fixes in future

Set manifest to use my device tree

---

manifests/sony_suzu.xml

Adds special android_build branch and droidmedia for further hardware enablement.

suzu: Build with droidmedia support

---

manifests/bq_gohan.xml

Now with improved formatting and less forks.

Add manifest for bq Aquaris X5 plus (gohan).

---

manifests/zte_axon7.xml

Move remote to different branch

---

manifests/sony_scorpion.xml
manifests/sony_scorpion_windy.xml

Removed the sepolicy part of the manifest as advised by @fredldotme on irc. This also means that a remote could be removed so I removed that too.

Removed unnecessary sepolicy parts

---

manifests/sony_dora.xml

manifests: Add support of Xperia X Performance

---

manifests/sony_kugo.xml

These are mostly updates directly from suzu. I'm also switching to the common sony/loire repos from @fredldotme.

Add some required components and use common loire platform repos

---

manifests/oneplus_oneplus2.xml

* import changes from personal repo to halium repo
* fix recovery for Ubuntu Touch

Oneplus2: multiple manifest changes

---

manifests/sony_suzu.xml

Also include required elfutils from AOSP.

suzu: Include fork of Sony's custom init & Kernel downgrade

---

manifests/xiaomi_mido.xml

Initial try for Halium 8.1 build.

Add Xiaomi Mido

---

manifests/xiaomi_rolex.xml

change remote source cause this remote has removed

fix missing remote

---

manifests/sony_dora.xml

We are still alive with suzu. ;)

sony_dora: Update

---

manifests/bq_tenshi.xml

some relative paths had duplicate entries

fix path typos in tenshi manifest

---

manifests/bq_tenshi.xml

another typo

---

manifests/bq_tenshi.xml

mea culpa, while fixing the other issue with the kernel branch name I introduced this error.
Change-Id: Ie5010390560b7f487a351eb6eeb3c4b33894c71f

hal refers to github and not the Halium group

---

manifests/bq_tenshi.xml

Issue in camera driver at vendor

Corrections in bq_tenshi.xml

---

manifests/samsung_trlte.xml

Samsung Galaxy Note 4 and the variants that I have reported to me as working from people that have tested other variants along with my UBports Recovery fixes that work on Galaxy Note 4

Samsung Galaxy Note 4

---

manifests/oneplus_fajita.xml

This should also work on OnePlus6 (enchilada) without any problems.
https://github.com/ubports-oneplus6 - Everything is being documented there

Added manifest for OnePlus6T (fajita)

---

manifests/xiaomi_sagit.xml

Add Xiaomi MI6 (sagit) manifest

manifests: include Xiaomi MI6 (sagit)

---

manifests/oneplus_bacon.xml

Change-Id: I7e543eee49ba767250642602f8f77cb8fa8a8801

Add Oneplus One (bacon) manifest

---

manifests/huawei_angler.xml

After syncing up all changes from Vince and Rargente we can start using our recovery branch again.
Change-Id: I7ba041b95f4d0713848ec33a9406e98f9d55a38a

Switch to UBports recovery repository

---

manifests/oneplus_cheeseburger.xml
manifests/oneplus_dumpling.xml

should I use an ssh remote instead of https? or a git?
```<remote name="Flohack74" fetch="ssh://git@github.com/Flohack74" revision="halium-9.0" />```
```<remote name="Flohack74" fetch="git://github.com/Flohack74" revision="halium-9.0" />```

manifests: include Oneplus5/5T (cheeseburger & dumpling)

---

manifests/xiaomi_rosy.xml

Change-Id: I3b1b23cb7287bc700f28136eccaf0b68a542e23e

Add Xiaomi rosy (Redmi 5)

---

manifests/oneplus_enchilada.xml
manifests/oneplus_fajita.xml

I had to add back some external projects to make it build on my system, I'm not sure that this is applicable to everyone who's tried to build this.

oneplus6: add enchilada and cleanup formatting

---

setup

Fix conditional mistake

---

manifests/xiaomi_laurel_sprout.xml

I finally got around doing this. It's currently untested but I'll update y'all once I've put it under testing.

Add manifest for Xiaomi Mi A3 (laurel_sprout)

---

manifests/xiaomi_whyred.xml

CPU : Snapdragon 636
GPU : Adreno 512
Linux : 4.4.y
Android : 7.1 / 8.1 / 9.0 / 10.0 / 11

Manifest: Add Xiaomi Redmi Note 5 Pro/AI [ Whyred ]

---

manifests/oneplus_bacon.xml

@Vince1171 thats one for you ;)

Refactor bacon a bit

---

manifests/xiaomi_violet.xml

Change-Id: Ide9a47b44c71869d7569471083ae0af248265a5c

manifests: add Xiaomi Redmi Note 7 Pro (violet)

---

manifests/xiaomi_vince.xml

Add Xiaomi redmi 5 plus(vince)

---

manifests/samsung_j3xlte.xml

Change-Id: Ie609c6f3ca7eabeea40e19e5c9d3e4e5b500944b

Add Samsung J3 (SM-J320F), codename `j3xlte`

---

manifests/xiaomi_mido.xml

halium-devices: Add support for Xiaomi Mido using Halium 9.0

---

manifests/motorola_albus.xml

Currently working on porting Halium 9 on my old Moto Z2 Play. Audio, NFC and Camera aren't working yet. Everything else works till now.

Add Motorola Moto Z2 Play [Albus] Manifest

---

manifests/bq_tenshi.xml
manifests/fairphone_FP2.xml
manifests/htc_m7.xml
manifests/huawei_angler.xml
manifests/lge_h815.xml
manifests/oneplus_bacon.xml
manifests/oneplus_oneplus2.xml
manifests/oneplus_oneplus3.xml
manifests/samsung_trlte.xml
manifests/sony_dora.xml
manifests/sony_kagura.xml
manifests/sony_kugo.xml
manifests/sony_suzu.xml
manifests/xiaomi_land.xml
manifests/xiaomi_rolex.xml
manifests/xiaomi_santoni.xml

This might need check by every porter, but I think its a necessary change. Tagging @fredldotme @APokorny @NotKit for the first iteration

Switch all devices again to UBports recovery

---

manifests/oneplus_cheeseburger.xml
manifests/oneplus_dumpling.xml

https://gitlab.com/ubports/porting/community-ports/android9/oneplus-5
Ping @Flohack74 for testing and carrying out this change on CI without breaking everything due to the `repo` mess :)

manifests: Migrate cheeseburger & dumpling repos to UBports GitLab

---

manifests/volla_yggdrasil.xml

https://gitlab.com/ubports/porting/reference-device-ports/android9/volla-phone
Ping @Flohack74 for sorting out the CI afterwards similar to #360 :)

manifests: Migrate volla_yggdrasil repos to UBports GitLab
