Halium/halium-devices

- yuga/manifest.xml
Also added a replacement for hardware/qcom/media-caf/msm8960 that
removes unneeded Java code.
> yuga: Correct remotes and restructue

- manifests/fairphone_FP2.xml
Fixes #11 
Kernel is still uploading to https://github.com/Halium/android_kernel_fairphone_msm8974, I'm planning to push the halium-5.1 branch from @peat-psuwit there too.
Note, that I didn't test anything, I'm just pushing my old branches that presumably worked at some point to the repository.
> Update repositories for Fairphone 2

- manifests/sony_castor.xml
- manifests/sony_castor_windy.xml
- manifests/sony_sirius.xml
- manifests/sony_z3.xml
- manifests/sony_z3c.xml
- manifests/sony_z3dual.xml
This includes the devices:
* Sony Xperia Z2 (sirius)
* Sony Xperia Z2 Tablet (castor)
* Sony Xperia Z2 Tablet WiFi (castor_windy)
* Sony Xperia Z3 (leo, z3)
* Sony Xperia Z3 Compact (aries, z3c)
* Sony Xperia Z3 Dual-SIM (z3dual)
The scorpion and scorpion_windy devices were already added, but also belong to
the shinano common devices.
I tested all manifests, they clone and compile successfully.
> Add sony shinano common devices

- manifests/motorola_lux.xml
- manifests/motorola_merlin.xml
- manifests/motorola_osprey.xml
- manifests/motorola_surnia.xml
This includes the devices:
* Motorola Moto G3 Turbo (merlin)
* Motorola Moto E 2015 LTE (surnia)
* Motorola Moto G 2015 (osprey)
* Motorola Moto X Play (lux)
The Motorola Moto G4 Play also belongs to the msm8916-common platform, but is
already included. I only removed unnecessary `revision` attributes there.
> Add motoroal msm8916-common devices

- manifests/samsung_hlte.xml
- manifests/samsung_hltechn.xml
- manifests/samsung_hltetmo.xml
- manifests/samsung_klte.xml
- manifests/samsung_kltechn.xml
- manifests/samsung_klteduos.xml
- manifests/samsung_kltedv.xml
- manifests/samsung_kltekdi.xml
- manifests/samsung_kltekor.xml
- manifests/samsung_kltespr.xml
- manifests/samsung_kltesprsports.xml
- manifests/samsung_kltetechnduo.xml
- manifests/samsung_klteusc.xml
- manifests/samsung_kltevzw.xml
This includes the devices:
* Samsung Galaxy Note 3 LTE (N9005/P) (hlte)
* Samsung Galaxy Note 3 (China) (hltechn)
* Samsung Galaxy Note 3 LTE (N900T/V/W8) (hltetmo)
* Samsung Galaxy S5 LTE (G900AZ/F/M/R4/R7/T/V/W8,S902L) (klte)
* Samsung Galaxy S5 LTE (China) (G9006V/8V) (kltechn)
* Samsung Galaxy S5 LTE Duos (G900FD/MD) (klteduos)
* Samsung Galaxy S5 LTE (G900I/P) (kltedv)
* Samsung Galaxy S5 LTE (SCL23) (kltekdi)
* Samsung Galaxy S5 LTE (G900K/L/S) (kltekor)
* Samsung Galaxy S5 Sprint (G900P) (kltespr)
* Samsung Galaxy S5 Sport (kltesprsports)
* Samsung Galaxy S5 China Dual-SIM (G9006W/G9008W/G9009W) (kltechnduo)
* Samsung Galaxy S5 USC (G900R4/G900R7) (klteusc)
* Samsung Galaxy S5 Verizon (G900V/S902L) (kltevzw)
Hello, Samsung - One mobile phone + one tablet = 14 different devices
> Add samsung klte/hlte common devices

- manifests/motorola_potter.xml
Yes, really, it has to use bluedroid from cm12.1. It won't build without it in the tree.
> Add manifest for potter

- huawei_angler.xml
- manifests/huawei_angler.xml
As of the time of posting this, the system image fails to build.
Here's the output from `mka systemimage`:
```
make: Entering directory '/home/********/Public/Nexus6P/ports/code/Halium'
============================================
PLATFORM_VERSION_CODENAME=REL
PLATFORM_VERSION=7.1.1
LINEAGE_VERSION=14.1-20180204-UNOFFICIAL-angler
TARGET_PRODUCT=lineage_angler
TARGET_BUILD_VARIANT=userdebug
TARGET_BUILD_TYPE=release
TARGET_BUILD_APPS=
TARGET_ARCH=arm64
TARGET_ARCH_VARIANT=armv8-a
TARGET_CPU_VARIANT=cortex-a53
TARGET_2ND_ARCH=arm
TARGET_2ND_ARCH_VARIANT=armv7-a-neon
TARGET_2ND_CPU_VARIANT=cortex-a53.a57
HOST_ARCH=x86_64
HOST_2ND_ARCH=x86
HOST_OS=linux
HOST_OS_EXTRA=Linux-4.10.0-38-generic-x86_64-with-LinuxMint-18.3-sylvia
HOST_CROSS_OS=windows
HOST_CROSS_ARCH=x86
HOST_CROSS_2ND_ARCH=x86_64 …
```
> Add Nexus 6P (angler)

- manifests/bq_chaozu.xml
The halium-7.1-bq branch for the kernel includes a kernel forked from the official bq version, so the driver for the Aquaris U touch screen is included
> chaozu: Update manifest

- manifests/samsung_herolte.xml
- manifests/samsung_hlte.xml
- manifests/samsung_hltechn.xml
- manifests/samsung_hltetmo.xml
- manifests/samsung_klte.xml
- manifests/samsung_kltechn.xml
- manifests/samsung_klteduos.xml
- manifests/samsung_kltedv.xml
- manifests/samsung_kltekdi.xml
- manifests/samsung_kltekor.xml
- manifests/samsung_kltespr.xml
- manifests/samsung_kltesprsports.xml
- manifests/samsung_kltetechnduo.xml
- manifests/samsung_klteusc.xml
- manifests/samsung_kltevzw.xml
These repositories were located at https://github.com/LNJ2/*, but were moved to
the Halium organisation since near every samsung device will need the fixes
included in these repositories.
> samsung: Use hardware and qcom-commmon from Halium org.

- setup
apks now only need to be removed from device/$vendor/$codename/proprietary-files.txt. This makes forking the vendor repository unneccesary, only the device tree needs to be changed.
Probably fixes #21
> Automatically refresh vendor repository

- manifests/motorola_harpia.xml
- manifests/motorola_lux.xml
- manifests/motorola_merlin.xml
- manifests/motorola_osprey.xml
- manifests/motorola_surnia.xml
This replaces the kernel and common device tree repositories of the motorola
msm8916-common devices to the ones from Halium. They were moved from @lnj2 to
@halium on GitHub.
> motorola-msm8916-common: Use kernel & device tree from Halium

- setup
This should help with getting initial Halium build to build successfully
at least. In some cases it might get rid of the requirement to fork the
device repo.
> setup: Remove apk/jar files from proprietary-*.txt

- setup
*Quite often large manufacturers like Sony, Motorola, Samsung etc make multiple variants of a phone which share common repo's. We often need to patch those to remove the apk and jar files. This update will take care of that.
*Remove the context= lines from fstab files since these are for SELinux
which we don't support.
*Allow for additional proprietary file names to be covered such as
common-proprietary-files.txt
*Add some more logging
*Move from tabs to 4 spaces since the manifests use the same.
Signed-off-by: Herman van Hazendonk github.com@herrie.org
> Setup: Unify coding style & more automation for common folders and fstab

- setup
Output is also slightly changed, and now looks like this:
```
*****************************************
I: Configuring for device lge_mako
*****************************************
[ shortened ]
Syncing work tree: 100% (215/215), done.  
*******************************************
I: Refreshing device vendor repository: vendor/lge/mako
I: Processing proprietary blob file: ./proprietary-blobs.txt
I: Processing fstab file: ./fstab.mako
*******************************************
```
> setup: Improve coding style

- setup
Cleanup commit cdc7a2d broke the export for PLATFORM_COMMON.
> Fix issue introduced by cleanup cdc7a2d

- setup
Seems that the LiveWallPaper feature in 5.1 causes havoc during build.
It's not an apk/jar so we kill it by removing it completely from the .mk and .sh
files in device, device common, vendor and vendor common folders.
This should help first time porters to get an image to build without forking & manually patching.
Signed-off-by: Herman van Hazendonk github.com@herrie.org
> setup: Kill the LiveWallPaper feature

- manifests/bq_chaozu.xml
chaozu got upstream support by LineageOS, so quite a few things can be rebased or moved to upstream.
> Update chaozu manifest

- manifests/hp_tenderloin.xml
- manifests/lge_mako.xml
Add HP Touchpad (tenderloin) and Google/LG Nexus 4 (mako) targets that are using 5.1 on LuneOS
> Add 5.1 targets used by LuneOS

- manifests/xiaomi_tissot.xml
Add Xiaomi A1 (tissot) support.
Unfortunately the device and vendor repos needed quite some work before they were useful. Patches have been sent upstream to tissot-dev, however seems it's not very active, so linking my own repos for now.
> Add Xiaomi A1 (tissot)

- manifests/oneplus_onyx.xml
Project path for kernel contained the wrong name, this has now been addressed and switching to corpuscle's kernel which is using newer CM14.1 kernel v.s. Halium.
> Onyx.xml: Fix kernel repo

- manifests/sony_ivy.xml
This is essentially the same as the Sony Z5 port - It uses the same kernel with updated apparmor and an adapted kernel config.
> Add Device Sony Z3+ (Z4) Ivy derived from an updated Sony Z5 (sumire) config

- manifests/sony_suzu.xml
This manifest replaces and removes some default repositories:
* Removal of Qualcomm SELinux policies
* ~bionic: Support for loading binaries and libraries from /odm~
* Qualcomm display HAL: Added "(AOSP)" suffix
* ~Qualcomm Dataservices: AOSP build~
> suzu: Add manifest for Sony Xperia X

- manifests/motorola_addison.xml
The device is tested to boot into UBPorts rootfs, but currently requires some hacks for halium-boot due to using F2FS and having console=null kernel cmdline argument coming from bootloader.
> Add Moto Z Play (addison)

- manifests/dell_bb.xml
This is my local manifest to add the Dell Venue 7840 (Blackburn, bb). This also works for the Dell Venue 7040 (Eaglespeak, ep) which feature basically the same hardware.
The repos are forked from the Asus Z00A (a smartphone). (Which also features almost the same hardware).
However, I cannot provide vendor files due to legal concerns.
For now, you need to manually install those files: grab the vendor blobs from Asus Z00A instead e.g. from Github "The Muppets" and change any occurence of "Z00A" to "bb" (also path names).
> Add Dell Venue 7840 (Blackburn, bb)

- manifests/huawei_angler.xml
Updated manifest for Nexus 6p (Huawei Angler), links to repos forked from LineageOS with changes relevant to Halium included, based on discussion in https://github.com/Halium/projectmanagement/issues/56
> angler: Update Nexus 6p (angler) manifest

- setup
The folder CMActions, when present, is not deleted by the function removedUnneededFolders since the A is capitalized, causing errors in later steps of the build process.
> Added possibility A is capitalized in removeUnneededFolders

- manifests/fairphone_FP2.xml
The repo from FairBlobs are outdated and isn't in sync with new
LineageOS branch.
Change-Id: I994d6ae1a0da6b91feaae370998eaa77c75e01ee
> FP2: use vendor repo from "them"

- manifests/sony_suzu.xml
This patched version is required to get call audio working.
Long term plan is to merge required commits into Haliums Non-CAF Audio HAL.
> suzu: Use modified AOSP Audio HAL

- manifests/sony_suzu.xml
This replaces the default AOSP-provided media HAL with a custom HAL with compile fixes,
uses libhybris with camera fixes (until it's merged) and provides a system-image-upgrader compatible recovery.
> suzu: Use patched media HAL, libhybris & recovery

- manifests/sony_suzu.xml
gpg and updated toybox (for fixed 'tar' command) are required by the UBports system-image-upgrader.
Rooted adbd is used to match behaviour of TWRP and fulfill ubuntu-device-flash requirements.
> suzu: libhybris, add gpg and updated toybox, use rooted adb

- manifests/sony_kugo.xml
The new kernel branch is a minimal set of changes to the Suzu kernel, this should make maintaining both devices easier.
Other changes are from the Suzu config.
> Update Kugo manifest

- manifests/sony_dora.xml
Most repositories do not need to be adapted, additionally all ftbfs issues in the kernel repository were recently resolved.
> reuse fredldotme repositories for dore/tone

- manifests/sony_kugo.xml
The kugo defonfig is now included in @fredldotme's loire kernel repo. We can now use the same repo for both suzu and kugo kernels.
> use common loire kernel repo

- manifests/sony_dora.xml
I forgot to set the name back to fredls kernel repository name when moving from sjllls.
> fix reponame for dora

- manifests/xiaomi_beryllium.xml
- manifests/xiaomi_land.xml
- manifests/xiaomi_mido.xml
To GitLab to solve issue with Xiaomi vendor that was removed from GitHub.
> manifests: Xiaomi Beryllium, Land and Mido: Update vendor repo

- manifests/huawei_angler.xml
I am not sure how we gonna deal with this situation:
- Originally Halium was meant to be a common base for all our OSes
- Now at least until next year, Ubuntu Touch will not be able to have the same kernel configs as "real" Halium devices (and I doubt that especially with Bluetooth and apparmor this will ever be the case)
- systemd is not even close for us (but will be considered for 20.04 upgrade)
- Our current CI pipeline is made so it will try to fetch the manifest from here
Thats quite contradicting. I dont want a fight between maintainers of ports since they have only 1 source of truth for the manifest.
@bhush9 @mariogrip what are we doing about this?
Nevertheless I am pushing my "Ubuntu Touch" manifest here, since otherwise I am blocked with releasing it via our CI (which i …
> Update huawei_angler (adapted to Ubuntu Touch)

- manifests/sony_dora.xml
- manifests/sony_kagura.xml
- manifests/sony_kugo.xml
- manifests/sony_suzu.xml
This fork (which is mine) contains a fix for enabling Macaddrsetup on
Android 7. This, together with changes in device-sony-common and kernel-
device-loire, allows for correct Wi-Fi MAC address instead of randomized
or default one.
Change-Id: I2a8abb073f267caf30716f295dc281a6d1163e59
> Switch macaddrsetup for Sony loire devices to peat-psuwit fork

- setup
Google Pixel device tree contains both devices in LOS sources. Needs hacks to not break setup script:
- Device tree has subdirectories for each device, that need to be scanned for additional pruning
- Also, setup script needs to be aware that when sailfish is selected, use marlin directory name instead
> Fix Google Pixel setup

- setup
This PR will add capabilities to correctly set up devices that are contained in a multi-device-manifest. You can basically do the following:
* Add a manifest containing common and device-specific repos for 2 devices and name it vendor_device1_device2.xml
* Start setup as usual with the device name
* It will check all xml files in the manifests folder to extract the vendor, and then make a substring compare on the remaining part
This will not affect that many devices, but it can help us keep manifests tidy.
> Correctly identify manifests which contain  more than 1 device

- manifests/google_sailfish_marlin.xml
Since LineageOS decided to put both devices into the same device repo, we follow that idea and so this manifest can build both devices. See also #281 
Change-Id: I91f781f461a46e5d272fcb8f3bf8c5433d54f17f
> Add Google Pixel and Pixel XL in one manifest

- manifests/samsung_herolte.xml
Update device manifest to reflect the latest developments on the WIP UBport Ubuntu Touch port. The repos specified include all the changes specified in the UBports porting guide and the halium-boot.img and system.img produced will boot directly into Ubuntu Touch, although not everything functions yet.
> Update samsung Galaxy S7 (herolte) manifest

- manifests/xiaomi_tissot.xml
For the setup script, the idea is that we often have missing entries in the proprietary-files.txt files.
I don't see any use-case where we wouldn't want to include some of the files in the proprietary vendor repos, so in the setup script I try to add missing files in proprietary-files.txt.
> Add Xiaomi Tissot (A1) manifest

- manifests/fairphone_FP2.xml
This MR adjusts the FP2 manifest to use the ubports recovery image.
> Let FP2 use ubports recovery image

- manifests/oneplus_onyx.xml
Build  and boot to uports7.1
Tree: halium-7.1
> onyx: use more up-to-date repos

- setup
Thats another weird case: Google Pixel 2 was originally announced as being codename muskie, so LineageOS seems to have tried to follow that name, and already set up everything, when Google decided that the codename will be changed to walleye.
So now for devicename walleye we have to change the device tree name again back to muskie, since that is hardcoded all over the place. In a follow-up commit I will present a manifest that can be used together with that change.
Device setup script does many assumptions about directory names based on device name. We should eventually do it similar as LOS, to actually find the files in the subdirs, parse them and learn about which device is located where.
The changes to echo lines is following on the changes also for Pixel: We should print the effective …
> Add hack for Google Pixel 2/2XL

- manifests/google_walleye_taimen.xml
Note that despite the name containing walleye, the device repo for Pixel 2 is called muskie. Thats intentional and was messed up by Google themselves. See also #284 
Change-Id: I5e3835f4f55030f417d3ab8f13b837f3bd667a20
> Add manifest for Google Pixel 2/2XL

- manifests/lge_hammerhead.xml
This is a Halium-9.0 port for hammerhead.
> Add manifest for LG Nexus 5 (hammerhead)

- manifests/lge_mako.xml
Initial port of LG Mako (Nexus 4) to Halium 9.0.
> halium-devices: Add Halium 9.0 port of LG Mako (Nexus 4)

- manifests/asus_Z00ED.xml
We've moved the device sources to the UBports Z00E GitHub organization. Old sources were deleted, so this manifest should be updated.
> Move ASUS Z00ED sources to UBports Z00E organization

- setup
On some devices like tissot, the fstab file isn't suffixed with a dot
> Look for fstab* instead of fstab.*

- manifests/lge_h815.xml
This manifest has been modified for building UBports recovery as well as halium-boot.img and system.img. All have been built and tested.
> Add manifest for LG G4 (h815)

- setup
Fix the script to allow use of Darwin-isms when Linux is not used.
> setup: Enable support for macOS

- manifests/bq_tenshi.xml
- manifests/fairphone_FP2.xml
- manifests/htc_m7.xml
- manifests/huawei_angler.xml
- manifests/lge_h815.xml
- manifests/oneplus_bacon.xml
- manifests/sony_dora.xml
- manifests/sony_kagura.xml
- manifests/sony_kugo.xml
- manifests/sony_scorpion.xml
- manifests/sony_scorpion_windy.xml
- manifests/sony_suzu.xml
This caught us offguard and destroyed H7.1 builds in a very random way. But git:// is no longer usable when unauthenticated. Use https instead
> Change URL scheme according to Github SecOps changes

- setup
This fixes device manifest setup without the need
for GNU Coreutils to be present on macOS.
> setup: Fix finding device manifests on macOS

- setup
Instead of fetching network and then doing a local checkout,
do a normal repo sync which fetches and then checks out.
> setup: do only one repo sync run

- setup
Recently we had a broken repo version that was choking on certain manifests that used "remove-project" a lot. The error was only visible on the initial sync of the CI script. When those errors were fixed subsequent errors in the setup script (after device manifest has been added" went unnoticed.
We need to check repo´s return code all times to prevent broken builds or regressions even (dropped ril and camera functionality on the Sony Xperia X e.g.)
> Evaluate repo sync return code and stop in case of error

- manifests/google_sargo.xml
The Pixel 3a has been promoted as one of the new Reference Device Ports. Adapt URLs to their new locations.
> manifests: Adapt to new sargo URLs

- manifests/xiaomi_violet.xml
This repository is used when building the vendor image:
https://gitlab.com/ubuntu-touch-xiaomi-violet/android_vendor_xiaomi_violet/-/blob/halium-9.0/violet-vendor.mk#L1302
Change-Id: I49e337d19548ebe1dc5446223a3326cb29898c42
> devices: add FM radio repository to xiaomi_violet

- setup
This became necessary since Oneplus has 2nd vendor oppo, and since Lineage 16.0 they have a common repo also in oppo folder, which was not stripped properly until now.
> Refactor setup script, consider 2nd vendor properly

- setup
- Use glob instead of the output of ls. (https://www.shellcheck.net/wiki/SC2045)
- Add spaces around comparision operator `=`. (https://www.shellcheck.net/wiki/SC2077)
> setup: correct ShellCheck critical errors
